userapp/urls.py
from django.urls import path
from userapp import views
from userapp.views import *
app_name = 'userapp'


urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('login/',views.user_login,name="login"),
    path("registration/",views.registration,name="registration"),
    path('logout/',views.user_logout,name='logout'),
    # path('apply/<int:pk>/',views.applyuserapp,name="apply"),
    path('update/',views.update,name="update"), 
    path('profile/',views.user_profile,name="profile"),
    path('ty/',views.ty,name="ty"),
    path("blogpost/",views.blogdata,name="blogpost"),
    path("blog/",views.blog,name="blog"),
    path("blogdetails/<int:id>/",views.blogdetail,name="blogdetails"),
    path("authordata/<int:user_id>/",views.authorview,name="author"),
    path("search/",views.search,name="search"),
    path("likes/<int:id>/",views.likes,name="likes"),
    path("likedata/",views.likesdata,name="likedata"),
    path('bookmark/<int:id>/', views.bookmark, name='bookmark'),
    path("bookmarkdata/",views.bookmardata,name="bookmarkdata"),
    path("forgotpassword/",views.forgotpassword,name="forgotpassword"),
    
]

userproject/jobpostdata/urls.py
from django.urls import path
from jobpostdata import views

app_name = 'jobpostdata'

urlpatterns = [
    path('',views.jobdetails,name="jobdetails"),
    path('apply',views.applyuserapp,name="apply"),
    path('<int:pk>/', views.job_display, name='job_display'),
    path('appliedjobs/',views.appliedjobs, name="appliedjobs"),
]

userproject/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp.views import *
from django.conf.urls.static import static
from django.conf import settings


from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('',include("userapp.urls")),
    path('jobpost/',include("jobpostdata.urls")),
    path('admin/', admin.site.urls),
    path('password-reset/', PasswordResetView.as_view(template_name = "password_reset.html"),name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="password_reset_done.html"),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name='password_reset_complete'),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

userproject/userapp/urls.py
from django.urls import path
from userapp import views

app_name = 'userapp'

urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('login/',views.user_login,name="login"),
    path("registration/",views.registration,name="registration"),
    path('logout/',views.user_logout,name='logout'),
    path('update/',views.update,name="update"), 
    path('profile/',views.user_profile,name="profile"),
    path('ty/',views.ty,name="ty"),
    path("blogpost/",views.blogdata,name="blogpost"),
    path("blog/",views.blog,name="blog"),
    path("blogdetails/<int:id>/",views.blogdetail,name="blogdetails"),
    path("authordata/<int:user_id>/",views.authorview,name="author"),
    path("search/",views.search,name="search"),
    path("likes/<int:id>/",views.likes,name="likes"),
    path("likedata/",views.likesdata,name="likedata"),
    path('bookmark/<int:id>/', views.bookmark, name='bookmark'),
    path("bookmarkdata/",views.bookmardata,name="bookmarkdata"),

]

userproject/jobpostdata/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from userapp.models import  userdetails


# Create your models here.
class Jobdata(models.Model):
    
    job_title = models.CharField(max_length=100)
    description = models.CharField(max_length=2000)
    company = models.CharField(max_length=100)
    posted_on = models.DateTimeField()
    location = models.CharField(max_length=100)
    salary = models.IntegerField()
    type = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.job_title
    
    

class applyjobs(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    jobtitle = models.ForeignKey(Jobdata,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    pg = models.CharField(max_length=100,null=True,blank=True)
    degree = models.CharField(max_length=100)
    PU = models.CharField(max_length=100)
    school = models.CharField(max_length=100)
    resume = models.ImageField(upload_to='resume/' ,blank=True)
    
    def __str__(self):
        return self.first_name
    
 

userproject/jobpostdata/forms.py
from django import forms
from jobpostdata.models import applyjobs


class applyuser(forms.ModelForm):
    class Meta:
        model = applyjobs
        fields = ["jobtitle","first_name","last_name","email","phone","pg","degree","PU","school","resume"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Apply a black border to all fields
        for field_name, field in self.fields.items():
            if isinstance(field.widget, (forms.TextInput, forms.Textarea)):
                field.widget.attrs.update({'style': 'border: 2px solid grey;'})

userproject/jobpostdata/views.py
from django.shortcuts import render,get_object_or_404

# Create your views here.
from django.shortcuts import render,redirect,HttpResponse
from jobpostdata.models import Jobdata,applyjobs
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from jobpostdata.forms import applyuser
from django.shortcuts import render, get_object_or_404

# Create your views here.

@login_required(login_url='userapp:login')   
def jobdetails(request):

    jobs = Jobdata.objects.all()
    return render(request,"jobpost/jobdetails.html",{"jobs":jobs})


def job_display(request, pk):
    details = get_object_or_404(Jobdata, pk=pk)
    return render(request, 'jobpostdata/Jobdata_detail.html', {'details': details})

# class JobDisplay(DetailView):

#     context_object_name = "details"

#     model = Jobdata


@login_required(login_url='userapp:login')
def applyuserapp(request):
    jobdata = Jobdata.objects.all()

    if request.method == 'POST':
        formuser = applyuser(request.POST, request.FILES)
        formuser.instance.user = request.user  # Assign the current user to the job application

        # Extract the selected jobtitle from the form data
            # selected_jobtitle_id = request.POST.get('jobtitle')
            
            # # Set the jobtitle in the instance based on the selected jobtitle ID
            # if not formuser.instance.jobtitle:
            #     # Set a default job title based on some logic or condition
            #     default_jobtitle = Jobdata.objects.get(name='jobtitle')
            #     formuser.instance.jobtitle = default_jobtitle
            
        if formuser.is_valid():
            formuser.save()
            return redirect('userapp:ty')
    else:
        formuser = applyuser()

    return render(request, "apply.html", {"formuser": formuser, "jobdata": jobdata})



def appliedjobs(request):

    userjobs = applyjobs.objects.filter(user=request.user).select_related('jobtitle')

    print(userjobs)
    
    return render(request,"appliedjobs.html",{"userjobs":userjobs})

# bk =  blogpost.objects.filter(bookmark=request.user)

#     return render(request,"bookmark.html",{"bk":bk})

 # Assuming applyuser is a Django form defined in forms.py
@login_required(login_url='userapp:login')
def applyuserapp(request, pk):
    # instance = get_object_or_404(applyjobs, pk=pk)
    # if request.method == 'POST':
    #     form = applyuser(request.POST, request.FILES, instance=instance)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('thank_you')  # Redirect to a thank you page upon successful update
    # else:
    # form = applyuser()
    return render(request, 'ty.html')

userproject/userapp/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,get_object_or_404
from userapp.forms import usrform,usr_update,usr_img,blogpostform,commentform,subscribeform,userprofile,subscribeform1
from .models import userdetails,User,blogpost,comments,subscribe
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from jobpostdata.models import Jobdata
# Create your views here.

def registration(request):
    registered =False

    if request.method=="POST":
        form= usrform(request.POST)
        profile=userprofile(request.POST,request.FILES)

        if form.is_valid and profile.is_valid :
            user = form.save()
            user.set_password(user.password)
            user.save()

            prof = profile.save(commit=False)
            prof.user = user 
            prof.save()
            registered = True
            return redirect('userapp:login')
    else:
        form = usrform()
        profile = userprofile()

    return render(request,"register.html",{"form":form,"profile":profile,"registered":registered})

def user_login(request):
    if request.method == 'POST':
        username= request.POST.get('username')
        password =request.POST.get('password')

        user= authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return redirect('userapp:home')
            else:
                return HttpResponse(" please check your creds")
        
        else:
            return HttpResponse("please check your creds")
        
    return render(request,"login.html",{})

def index(request):
    return render(request,"index.html")

@login_required(login_url='userapp:login')
def home(request):
    blogposts = blogpost.objects.all().order_by("-view_count")[0:3]
    top_post = blogpost.objects.all().order_by("-view_count")[0]
    newblog =  blogpost.objects.all().order_by("-time")[0:3]
    sub = subscribeform()
    
    saved = False
    error_message = None
    
    if request.method == "POST":
        sub = subscribeform(request.POST)
        if sub.is_valid():
            email = sub.cleaned_data['email']
            
            # Check if the email already exists
            if not subscribe.objects.filter(email=email).exists():
                # Save the subscription if the email does not exist
                sub.save()
                saved = True
            else:
                # Set an error message if the email already exists
                error_message = 'This email is already registered.'

    return render(request, "home.html", {"blogposts": blogposts, "sub": sub, "top_post": top_post, "saved": saved, "error_message": error_message,"newblog":newblog})

def user_logout(request):
    logout(request)
    return redirect('userapp:login')

@login_required(login_url='userapp:login')   
def update(request):
    if request.method == "POST":
         form =  usr_update(request.POST,instance=request.user) 
         form1 = usr_img(request.POST, request.FILES, instance=request.user.userdetails)
         if form.is_valid() and form1.is_valid():
             form.save()
             form1.save()
             return redirect('userapp:index')
    else:
        form = usr_update(instance=request.user)
        form1 = usr_img(instance=request.user.userdetails)
    return render(request,"update.html",{"form":form,"form1":form1})

@login_required(login_url='userapp:login')
def user_profile(request):

    userprofile = userdetails.objects.get(user = request.user)

    return render(request,"profile.html",{"userprofile":userprofile})

   

@login_required(login_url='userapp:login')
def ty(request):
    return render(request,"ty.html")

def blogdata(request):
    saved = False

    if request.method == "POST":
        blog_form = blogpostform(request.POST, request.FILES)

        if blog_form.is_valid():
            blog_post = blog_form.save(commit=False)
            blog_post.author_name = request.user
            blog_post.save()
            saved = True
            return redirect('userapp:blog')
        else:
            return HttpResponse("Data was not saved")

    else:
        blog_form = blogpostform()

    return render(request, "blogpost.html", {"blog": blog_form, "saved": saved})

def displayblog(request):

    data = blogpost.objects.all()

    return render(request,"displayblog.html",{"data":data})


def blog(request):
    blog = blogpost.objects.all()
    return render(request,"blog.html",{"blog":blog})

def blogdetail(request, id):
    post = get_object_or_404(blogpost, id=id)
    comment_form = commentform()

    # likes code
    liked = False
    if post.like.filter(id=request.user.id).exists():
        liked = True 
    post_is_liked = liked

    if request.method == "POST":
        comment_form = commentform(request.POST)
        if comment_form.is_valid():
            content = comment_form.cleaned_data['content']
            user = request.user


            post_sno = request.POST.get("postSno")
            print(post_sno)

            parent_sno = request.POST.get("parentSno")

            if parent_sno:
                parent = comments.objects.get(sno=parent_sno)
                comment1 = comments(content=content, user=user, post=post, parent=parent)
            else:
                comment1 = comments(content=content, user=user, post=post)

            comment1.save()

    if post.view_count is None:
        post.view_count = 1
    else:
        post.view_count += 1
    post.save()

    # Ensure that 'post' is defined even if the request method is not POST
    usercomments = comments.objects.filter(post=post).exclude(parent__isnull=False)
   
    reply = comments.objects.filter(post=post, parent__isnull=False)

    recentposts = blogpost.objects.all().order_by("-time")[0:3]
    topposts = blogpost.objects.all().order_by("-view_count")[0:3]

    recentposts_viewmore = blogpost.objects.all().order_by("-time")
    topposts_viewmore = blogpost.objects.all().order_by("-view_count")

    allblog = blogpost.objects.all()

    author_name = post.author_name

    relatedpost= blogpost.objects.exclude(id=id).filter(author_name=author_name)[0:2]

    comment1 = comments.objects.filter(post=post).exclude(parent__isnull=True).count()
    comment2 = comments.objects.filter(post=post).exclude(parent__isnull=False).count()
    total_comment = comment1+comment2
    no_of_likes = post.no_of_like

  

    context = { 'post': post, 
                'form': comment_form,
                'usercomments': usercomments,
                'reply': reply,
                "topposts":topposts,
                "recentposts":recentposts,
                "total_comment":total_comment,
                "rv":recentposts_viewmore,
                "tv":topposts_viewmore,
                "allblog":allblog,
                'post_is_liked':post_is_liked,
                'no_of_likes':no_of_likes,
                'relatedpost':relatedpost,
                
                }
    return render(request, 'blogdetail.html', context)

def likes(request, id):
   
    post_id = request.POST.get('post_id')
    print("post id",post_id)

    post = get_object_or_404(blogpost, id=request.POST.get('post_id'))

   
    if request.user in post.like.all():
        print("Removing like")
        post.like.remove(request.user)
    else:
        print("Adding like")
        post.like.add(request.user)

    return HttpResponseRedirect(reverse('userapp:blogdetails',args=[str(id)]))


def authorview(request, user_id):
    author_details = get_object_or_404(userdetails, user_id=user_id)
    return render(request, "authorview.html", {"author_details": author_details})


def search(request):
    posts = blogpost.objects.all()
    searched = request.GET.get('searched', '')
    blogs = []

    if searched:
        blogs = blogpost.objects.filter(post_title__icontains=searched)
   

    return render(request, "search.html", {"searched": searched, "blogs": blogs, "posts": posts})

def likesdata(request):

    # Retrieve the liked posts for the current user
    liked_posts = blogpost.objects.filter(like=request.user)

    return render(request, "like.html", {"liked_posts": liked_posts})


def bookmark(request, id):

    post = get_object_or_404(blogpost, pk= id)

    if request.user in post.bookmark.all():
        post.bookmark.remove(request.user)
    else:
        post.bookmark.add(request.user)

    return HttpResponseRedirect(reverse('userapp:blogdetails',args=[id]))

def bookmardata(request):

    bk =  blogpost.objects.filter(bookmark=request.user)

    return render(request,"bookmark.html",{"bk":bk})

userproject/templates/apply.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'jobpostdata:apply'   %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="container"><br>
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card card-body">                
                        {{formuser.as_p}}
                     
                    <center><input type="submit" class="btn btn-dark" style="width: 300px;"></center>
                   
                </div>
            </div>
        </div>
    </div>      
</div>
</form>

{% endblock %}

userproject/templates/authorview.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-6">
                <div class="card card-body">
                    <p>Author's Name : {{ author_details.user.username }}</p>
                    <p>Email : {{ author_details.user.email }}</p>
                    <p>Address : {{ author_details.address }}</p>
                    <p>LinkedIn : {{ author_details.linkedin }}</p>
                    <p>Facebook : {{ author_details.facebook }}</p>
                    <p>Instagram : {{ author_details.instagram }}</p>
                    <p>Twitter : {{ author_details.twitter }}</p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-body">
                    <img src="{{ author_details.user_img.url }}" alt="User Image" style="height: 300px;width: 300px;">

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

userproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'js/url.js' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/css.css' %}" />
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />
</head>
<style>
.navbar {
    /* Set background color to dark */
    height: 90px; /* Adjust the height as needed */
    
}
 .nav-link {
    color: white !important; /* Set text color to white */
    font-size: 18px; /* Adjust font size as needed */
}

.navbar-brand {
    color: white !important; /* Set text color to white */
    font-size: 24px; /* Adjust font size as needed */
}

.circular-image {
    border-radius: 50%;
    overflow: hidden;
    height: 60px; /* Adjust as needed to match the navbar height */
    width: 60px; /* Adjust as needed to match the navbar width */
}
.nav-link {
    display: flex;
    align-items: center;
    height: 100%; /* Ensure the nav-link takes full height */
}


.navbar-nav
{
    display: flex;
    align-items: center;
    height: 100%; /* Ensure the nav-link takes full height */
    padding-right: 40px;
} 

.navbar-item {
        margin-right: 30px; /* Adjust the value as needed */
        margin-block-start: auto;
    }

.ml-auto {
        margin-left: auto;
        
    }

</style>

<body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">  
      <ul class="nav navbar">
       
      <h2>  <a class="navbar-brand" href="#">VirtualSpace</a></h2>
        {% if user.is_authenticated %}
              <li class="nav-item">
                <p><a class="nav-link" ></a></p>
              </li>
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:home' %}">Home</a></p>
              </li>
                           
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'jobpostdata:jobdetails' %}">JobPost</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:blog' %}">Blog</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:profile' %}">Hello {{request.user}}</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:likedata' %}">Likes</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:bookmarkdata' %}">Bookmarks</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:logout' %}">Logout</a></p>
              </li>
              
            
              <!-- <form class="form-inline my-2 my-lg-0">
        
                <a href="{% url 'userapp:search' %}" class="btn btn-success">Search</a>
              </form> -->
              <li class="nav-item">
                <a class="nav-link" href="#">
                    {% if request.user.userdetails.user_img %}
                        <div class="circular-image justify-content-right">
                            <img src="{{ request.user.userdetails.user_img.url }}" alt="User Image" class="circular-image">
                        </div>
                    {% else %}
                        <div class="circular-image justify-content-right">
                            <img src="{% static 'images/image.png' %}" alt="Default Image" class="circular-image">
                        </div>
                    {% endif %}
                </a>
                
              </li>
          </ul>
          
          
          <form method="get" action="{% url 'userapp:search' %}" class="d-flex ml-auto">
            <input type="text" name="searched" placeholder="Search for blogs here" value="{{ searched }}" class="form-control" style="width: 190px;">
            <button type="submit" class="btn btn-dark ms-2">Search</button>
        </form>
        
        {% else %}
        <ul class="nav navbar">
              <li class="nav-item">
                <a class="nav-link" ></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userapp:registration' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userapp:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              
          {% endif %}

      </ul>
   

    </div>
    </nav>
    

      <a href="{% url 'userapp:home' %}" class="learn">
        <span class="material-icons"> keyboard_return </span> Go back
      </a>

             
      {% block content %}

      {% endblock %}
    
      <footer>
        <div class="container">
          <div class="grid-4">
            
            <div class="link">
              <h2>Quick link</h2>
              <div class="q-link">
                <a href="{% url 'userapp:home' %}">Home</a>
                <a href="">About</a>
                <a href="">All Post</a>
              </div>
            </div>
            <div class="link">
              <h2>Your Favourites</h2>
              <div class="q-link">
                <a href="{% url 'userapp:likedata' %}">Likes</a>
                <a href="{% url 'userapp:bookmarkdata' %}">Bookmarks</a>
              </div>
            </div>
            <div class="link">
              <h2>Top cetagory</h2>
              <div class="q-link">
                <a href="{% url 'userapp:home' %}">Home</a>
                <a href="#">VirtualSpace</a>
                <a href="#">Unsubscribe</a>
              </div>
            </div>
            
            <div class="news-signup">
              <h2>Subscribe</h2>
              <div class="newsletter">
                <form action="{% url 'userapp:home' %}" method="POST">
                  {% csrf_token %}
                  <input
                    type="email"
                    name="email"
                    maxlength="100"
                    placeholder="Enter your email"
                    required=""
                    id="id_email"
                  />
                  <button class="btn btn-primary">Subscribe</button>
                </form>
              </div>
          <div class="share">
            <div class="social">
              <a href="#">
                <i class="fa-brands fa-facebook-f"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-linkedin-in"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-twitter"></i>
              </a>
            </div>
          </div>
        </div>
      </footer> 
  
</body>
</html>

userproject/templates/blogpost.html
{% extends 'base.html' %}
{% block content %}

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card card-body">
                <form action="{% url 'userapp:blogpost' %}" method="POST" enctype="multipart/form-data" class="class-border">
                    {% csrf_token %}
                    {{blog.as_p}}
                    {% if saved %}
                    <h1>data was saved</h1>
                    {% endif %}
                    <button class="btn btn-primary">Add Post</button>

                </div>
            </div>
        </div>
    </div>
</div>




</form>


{% endblock %}

userproject/templates/bookmark.html
{% extends 'base.html' %}
{% load tz %}
{% block content %}


{% if bk %}
<main class="sp">
    <section class="sp">
        <div class="container">
            <h1 class="sec-title"> Displaying Bookmarked Post </h1>
            <div class="grid-3">
                {% for blog in bk %}
                    <a href="{% url 'userapp:blogdetails' blog.id %}">
                        <div class="card">
                            <div class="post-img">
                                {% if blog.image %}
                                    <img src="{{blog.image.url}}" alt="" />
                                {% else %}
                                    <h1>No image to display</h1>
                                {% endif %}
                                <div class="tag">{{blog.author_name}}</div>
                            </div>
                            <div class="card-content">
                                <h3>{{blog.post_title}}</h3>
                                <div class="author">
                                    <div class="profile-pic">
                                        {% if blog.author_name.userdetails.user_img %}
                                            <img src="{{blog.author_name.userdetails.user_img.url}}" style="height: 100%;" alt="" />
                                        {% endif %}
                                    </div>
                                    <div class="details">
                                        <p>{{blog.author_name.first_name}}</p>
                                        <small>{{ blog.time|timezone:blog.time_zone|date:"F j, Y H:i" }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>

</main>



{% else %}
<br>
<center><h1>You Have Not Bookmarked Any Post</h1></center>
{% endif %}
{% endblock %}

userproject/templates/ty.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card card-body">
                <img src="https://t4.ftcdn.net/jpg/02/02/78/81/360_F_202788149_9sndfcPPme9zRtstjROSmyLFma2UMYaM.jpg" style="height: 500px;height: 400px;">
                <h4>Thankyou for Applying!!! Your Data was Received </h4>
                <a href="{% url 'userapp:home' %}" class="btn btn-primary" style="width:200px;">Back</a>
                {{ form.as_p }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}