jobpostdata/urls.py
from django.urls import path
from jobpostdata import views

app_name = 'jobpostdata'

urlpatterns = [
    path('',views.jobdetails,name="jobdetails"),
    path('apply/<int:pk>/',views.applyuserapp,name="apply"),
    path('<int:pk>/', views.job_display, name='job_display'),
    path('appliedjobs/',views.appliedjobs, name="appliedjobs"),
]

userapp/urls.py
from django.urls import path
from userapp import views
from userapp.views import *
app_name = 'userapp'


urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('login/',views.user_login,name="login"),
    path("registration/",views.registration,name="registration"),
    path('logout/',views.user_logout,name='logout'),
    # path('apply/<int:pk>/',views.applyuserapp,name="apply"),
    path('update/',views.update,name="update"), 
    path('profile/',views.user_profile,name="profile"),
    path('ty/',views.ty,name="ty"),
    path("blogpost/",views.blogdata,name="blogpost"),
    path("blog/",views.blog,name="blog"),
    path("blogdetails/<int:id>/",views.blogdetail,name="blogdetails"),
    path("authordata/<int:user_id>/",views.authorview,name="author"),
    path("search/",views.search,name="search"),
    path("likes/<int:id>/",views.likes,name="likes"),
    path("likedata/",views.likesdata,name="likedata"),
    path('bookmark/<int:id>/', views.bookmark, name='bookmark'),
    path("bookmarkdata/",views.bookmardata,name="bookmarkdata"),
    path("forgotpassword/",views.forgotpassword,name="forgotpassword"),
    
]

userproject/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp.views import *
from django.conf.urls.static import static
from django.conf import settings


from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('',include("userapp.urls")),
    path('jobpost/',include("jobpostdata.urls")),
    path('admin/', admin.site.urls),
    path('password-reset/', PasswordResetView.as_view(template_name = "password_reset.html"),name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="password_reset_done.html"),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name='password_reset_complete'),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

userproject/userproject/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include("userapp.urls")),
    path('jobpost/',include("jobpostdata.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

userapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from timezone_field import TimeZoneField
from django.utils.text import slugify

# Create your models here.
class userdetails(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    user_img=models.ImageField(upload_to='userimages/',blank=True, default='userimages/image.png')
    address =models.CharField(max_length=200,blank=True)
    linkedin = models.CharField(max_length=200,blank=True)
    facebook = models.CharField(max_length=200,blank=True)
    instagram = models.CharField(max_length=200,blank=True)
    twitter = models.CharField(max_length=200,blank=True)
    time_zone = TimeZoneField(default='Asia/Kolkata')

    def __str__(self) -> str:
        return str(self.user)



class blogpost(models.Model):

    author_name = models.ForeignKey(User, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=200)
    post_title = models.CharField(max_length=200)
    sub_title = models.CharField(max_length=100,blank=True,null=True)
    description= models.TextField(max_length=10000)
    image = models.ImageField(upload_to='blogimages/',blank=True)
    time = models.DateTimeField(auto_now_add=True)
    view_count =  models.IntegerField(blank=True,null=True)
    time_zone = TimeZoneField(default='Asia/Kolkata')
    like = models.ManyToManyField(User,related_name="postlikes")
    bookmark = models.ManyToManyField(User, related_name="bookmarks")

    def __str__(self):
        return self.post_title
    
    def no_of_like(self):
        return self.like.count()
   
  


class comments(models.Model):

    sno = models.AutoField(primary_key=True)
    content = models.TextField(max_length=10000)
    date = models.DateTimeField(auto_now_add=True)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True,null=True)
    post = models.ForeignKey(blogpost, related_name="postdata", on_delete=models.CASCADE)
    parent =  models.ForeignKey('self' ,null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    time_zone = TimeZoneField(default='Asia/Kolkata')

    def __str__(self):
        return str(self.user)

class subscribe(models.Model):

    email= models.EmailField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    

templates/apply.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'jobpostdata:apply' instance.pk  %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="container"><br>
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card card-body">                
                        {{formuser.as_p}}
                     
                    <center><input type="submit" class="btn btn-dark" style="width: 300px;"></center>
                   
                </div>
            </div>
        </div>
    </div>      
</div>
</form>

{% endblock %}

templates/applyjob_form.html
{% extends 'base.html' %}
{% block content %}

<form action="{% url 'jobpostdata:apply' pk=instance.pk  %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="container"><br>
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card card-body">                
                        {{form.as_p}}
                     
                    <center><input type="submit" class="btn btn-dark" style="width: 300px;"></center>
                   
                </div>
            </div>
        </div>
    </div>      
</div>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'js/url.js' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/css.css' %}" />
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />
</head>
<style>
.navbar {
    /* Set background color to dark */
    height: 90px; /* Adjust the height as needed */
    
}
 .nav-link {
    color: white !important; /* Set text color to white */
    font-size: 18px; /* Adjust font size as needed */
}

.navbar-brand {
    color: white !important; /* Set text color to white */
    font-size: 24px; /* Adjust font size as needed */
}

.circular-image {
    border-radius: 50%;
    overflow: hidden;
    height: 60px; /* Adjust as needed to match the navbar height */
    width: 60px; /* Adjust as needed to match the navbar width */
}
.nav-link {
    display: flex;
    align-items: center;
    height: 100%; /* Ensure the nav-link takes full height */
}


.navbar-nav
{
    display: flex;
    align-items: center;
    height: 100%; /* Ensure the nav-link takes full height */
    padding-right: 40px;
} 

.navbar-item {
        margin-right: 30px; /* Adjust the value as needed */
        margin-block-start: auto;
    }

.ml-auto {
        margin-left: auto;
        
    }

</style>

<body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">  
      <ul class="nav navbar">
       
      <h2>  <a class="navbar-brand" href="#">VirtualSpace</a></h2>
        {% if user.is_authenticated %}
              <li class="nav-item">
                <p><a class="nav-link" ></a></p>
              </li>
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:home' %}">Home</a></p>
              </li>
                           
              <li class="nav-item">
                <p><a class="nav-link" href="{% url 'jobpostdata:jobdetails' %}">JobPost</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:blog' %}">Blog</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:profile' %}">Hello {{request.user}}</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:likedata' %}">Likes</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:bookmarkdata' %}">Bookmarks</a></p>
              </li>
              <li  class="nav-item">
                <p><a class="nav-link" href="{% url 'userapp:logout' %}">Logout</a></p>
              </li>
              
            
              <!-- <form class="form-inline my-2 my-lg-0">
        
                <a href="{% url 'userapp:search' %}" class="btn btn-success">Search</a>
              </form> -->
              <li class="nav-item">
                <a class="nav-link" href="#">
                    {% if request.user.userdetails.user_img %}
                        <div class="circular-image justify-content-right">
                            <img src="{{ request.user.userdetails.user_img.url }}" alt="User Image" class="circular-image">
                        </div>
                    {% else %}
                        <div class="circular-image justify-content-right">
                            <img src="{% static 'images/image.png' %}" alt="Default Image" class="circular-image">
                        </div>
                    {% endif %}
                </a>
                
              </li>
          </ul>
          
          
          <form method="get" action="{% url 'userapp:search' %}" class="d-flex ml-auto">
            <input type="text" name="searched" placeholder="Search for blogs here" value="{{ searched }}" class="form-control" style="width: 190px;">
            <button type="submit" class="btn btn-dark ms-2">Search</button>
        </form>
        
        {% else %}
        <ul class="nav navbar">
              <li class="nav-item">
                <a class="nav-link" ></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userapp:registration' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'userapp:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              
          {% endif %}

      </ul>
   

    </div>
    </nav>
    

      <a href="{% url 'userapp:home' %}" class="learn">
        <span class="material-icons"> keyboard_return </span> Go back
      </a>

             
      {% block content %}

      {% endblock %}
    
      <footer>
        <div class="container">
          <div class="grid-4">
            
            <div class="link">
              <h2>Quick link</h2>
              <div class="q-link">
                <a href="{% url 'userapp:home' %}">Home</a>
                <a href="">About</a>
                <a href="">All Post</a>
              </div>
            </div>
            <div class="link">
              <h2>Your Favourites</h2>
              <div class="q-link">
                <a href="{% url 'userapp:likedata' %}">Likes</a>
                <a href="{% url 'userapp:bookmarkdata' %}">Bookmarks</a>
              </div>
            </div>
            <div class="link">
              <h2>Top cetagory</h2>
              <div class="q-link">
                <a href="{% url 'userapp:home' %}">Home</a>
                <a href="#">VirtualSpace</a>
                <a href="#">Unsubscribe</a>
              </div>
            </div>
            
            <div class="news-signup">
              <h2>Subscribe</h2>
              <div class="newsletter">
                <form action="{% url 'userapp:home' %}" method="POST">
                  {% csrf_token %}
                  <input
                    type="email"
                    name="email"
                    maxlength="100"
                    placeholder="Enter your email"
                    required=""
                    id="id_email"
                  />
                  <button class="btn btn-primary">Subscribe</button>
                </form>
              </div>
          <div class="share">
            <div class="social">
              <a href="#">
                <i class="fa-brands fa-facebook-f"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-linkedin-in"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-twitter"></i>
              </a>
            </div>
          </div>
        </div>
      </footer> 
  
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/css.css' %}">

    <title>Document</title>
  </head>

  <body>
  
    <main class="sp">
      <div class="container">
        <center>
          <h4 class="title">Welcome to VirtualSpace</h4>
          <div class="typo">
           
            <p>
              Lorem ipsum began as scrambled, nonsensical Latin derived from
              Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
            </p>
          </div>
          <div class="newsletter" style="h1{color: #000;}">
            <form action="{% url 'userapp:home' %}" method="POST">
              {% csrf_token %}
                  <h1>{{ sub }}</h1>
              <button type="submit" class="btn btn-warning">Subscribe</button>
          </form>
          </div><br>
          {% if saved %}
                  <h1>User has subscribed successfully</h1>
              {% endif %}
              {% if error_message %}
                  <h1>{{ error_message }}</h1>
              {% endif %}
        </center>
      </div>
   
{% if top_post %}
<section class="sp">
  <div class="container">
    <div class="grid-2">
      <div class="post-img">
        {% if top_post.image %}
          <img src="{{ top_post.image.url }}" alt="Post Image" />
        {% else %}
          <h1>No image available</h1>
        {% endif %}
      </div>
      <div class="post-content">
        <div class="category">
          <p>Category: {{ top_post.category.name }}</p>
          <!-- Replace 'category.name' with the actual attribute for the category name -->
        </div>
        <h1>{{ top_post.post_title }}</h1>
        
        <p class="d-inline-flex gap-1">
          <h5>{{ top_post.description|linebreaksbr|truncatewords_html:100 }}</h5>
          <a class="btn btn-primary" href="{% url 'userapp:blogdetails' top_post.id %}">
            View more
          </a>
        </p>
      </div>
    </div>
  </div>
</section>
{% endif %}
    <section class="sp">
      <div class="container">
        <h1 class="sec-title">Top blogs</h1>
        <div class="grid-3">
          <!-- card -->
          {% for post in blogposts %}
          <a href="{% url 'userapp:blogdetails' post.id %}">
            <div class="card">
              <div class="post-img">
                {% if post.image %}
                <img src="{{post.image.url}}" alt="" />
                {% else %}
                <h1>No image to display</h1>
                {% endif %}
                <div class="tag">{{post.author_name}}</div>
              </div>
              <div class="card-content">
                <h3>
                 {{post.post_title}}
                </h3>
                <div class="author">
                  <div class="profile-pic">
                    {% if post.author_name.userdetails.user_img %}
                    <img src="{{post.author_name.userdetails.user_img.url}}" style="height: 100%;" alt="" />
                    {% endif %}
                  </div>
                  <div class="details">
                    <p>{{post.author_name.first_name}}</p>
                    <small>{{ post.time|timezone:post.time_zone|date:"F j, Y H:i" }}</small>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </a>
          <!-- card end-->
          <!-- card -->

          <!-- card end-->
        </div>
        <center>
          
          <a href=""><button class="btn btn-primary rounded view">
            View more <span class="material-icons"> trending_flat </span>
          </button></a>
        </center>
      </div>
    </section>
    <section class="sp">
      <div class="container">
        <h1 class="sec-title">New blogs</h1>
        <div class="grid-3">
          <!-- card -->
          {% for post in newblog %}
          <a href="{% url 'userapp:blogdetails' post.id %}">
            <div class="card">
              <div class="post-img">
                {% if post.image %}
                <img src="{{post.image.url}}" alt="" />
                {% else %}
                <h1>No image available</h1>
                {% endif %}
                <div class="tag">{{post.author_name.username}}</div>
              </div>
              <div class="card-content">
                <h3>
                  {{post.post_title}}
                </h3>
                <div class="author">
                  <div class="profile-pic">
                    {% if post.author_name.userdetails.user_img %}
                    <img src="{{post.author_name.userdetails.user_img.url}}" style="height: 100%;" alt="" />
                    {% endif %}
                  </div>
                  <div class="details">
                    <p>{{post.author_name.first_name}}</p>
                    <small>{{post.time|timezone:post.time_zone|date:"F j, Y H:i"}}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          {% endfor %}
          <!-- card end-->
          <!-- card -->
          </div>
        <center>
          <a href=""><button class="btn btn-primary rounded view">
            View more <span class="material-icons"> trending_flat </span>
          </button></a>
        </center>
      </div>
    </section>
    
    <script src="url.js" id="url"></script>
  </main>
  </body>
</html>
{{ redirect_to_login_immediately }}

{% endblock %}

templates/like.html
{% extends 'base.html' %}

{% block content %}
{% load tz %}
    
        <!-- Display search results or other content here -->
       
        {% if liked_posts %}
      <main class="sp">
          <section class="sp">
              <div class="container">
                  <h1 class="sec-title"> Displaying Liked Post </h1>
                  <div class="grid-3">
                      {% for blog in liked_posts %}
                          <a href="{% url 'userapp:blogdetails' blog.id %}">
                              <div class="card">
                                  <div class="post-img">
                                      {% if blog.image %}
                                          <img src="{{blog.image.url}}" alt="" />
                                      {% else %}
                                          <h1>No image to display</h1>
                                      {% endif %}
                                      <div class="tag">{{blog.author_name}}</div>
                                  </div>
                                  <div class="card-content">
                                      <h3>{{blog.post_title}}</h3>
                                      <div class="author">
                                          <div class="profile-pic">
                                              {% if blog.author_name.userdetails.user_img %}
                                                  <img src="{{blog.author_name.userdetails.user_img.url}}" style="height: 100%;" alt="" />
                                              {% endif %}
                                          </div>
                                          <div class="details">
                                              <p>{{blog.author_name.first_name}}</p>
                                              <small>{{ blog.time|timezone:blog.time_zone|date:"F j, Y H:i" }}</small>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </a>
                      {% endfor %}
                  </div>
              </div>
          </section>
  
      </main>
  
  
    
  {% else %}
  <br>
  <center><h1>You Have Not Liked Any Post Yet</h1></center>
  {% endif %}
  
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/css.css' %}" />
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />

    <title>Document</title>
  </head>
  <body data-new-gr-c-s-check-loaded="14.1071.0" data-gr-ext-installed="">
    


    <form action="{% url 'userapp:login' %}" method="POST" class="form">
      {% csrf_token %}

    <!-- <input type="hidden" name="csrfmiddlewaretoken" value="MECR6bZJ2eTGRnFWfg7G0KPfVjCYujKLFmIfzaLgUs4DP6wEVZjzX30xS2lzZtow"> -->
      <center>
        <h1 style="text-decoration: underline;">Login Form </h1>
        <div class="inputs">
          <div>
          <div class="search-bar s-active input">
            <input type="text" placeholder="Username" name="username">
            <div class="animated-search">
              <i class="uil uil-envelope-alt"></i>
            </div>
          </div>
          <div class="search-bar s-active input">
            <input type="password" placeholder="Password" name="password">
            <div class="animated-search">
              <i class="uil uil-key-skeleton"></i>
            </div>
          </div>
          
          </div>

          <!-- <button class="btn btn-primary rounded" type="submit">
            Login <span class="material-icons"> arrow_right_alt </span>
          </button> -->
          <button type="submit" class="btn btn-primary">Login</button>
          <p>Not have an account? <a href="{% url 'userapp:registration' %}">Sign up</a></p>
          <p>Did You Forgot your password!!! click here  <a href="{% url 'password_reset' %}">Forgot Password</a></p>
        </div>
      </center>
    </form>
    </main>
</body>
</html>
{% endblock %}

<!-- <style>
    h1{
        font-family:Georgia, 'Times New Roman', Times, serif;
        text-decoration: underline;
    }
    
    body{
        background-image: url(https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);
        background-size: cover;
    }

</style>
<body>
  <form action="{% url 'userapp:login' %}" method="POST">
    {% csrf_token %}
    <br><br><br><br>

    <div class="container">
      <div class="jumbotron">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">
                <center><h1>Login Form</h1></center>

                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" placeholder="Enter your username" required>
                </div><br>

                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" name="password" class="form-control" placeholder="Enter your password" required>
                </div><br>
              <h5><a href="#">Forgot password</a></h5><br>

                <button type="submit" class="btn btn-dark" style="width:600px;">Submit</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</body>

templates/password_reset.html
{% extends 'base.html' %}
{% block content %}

<style>
	.btn-send,
.btn-cancel {
    display: inline-block;
    width: 100px;
	margin-right: 5px;
}

/* Optionally, you can add margin between the buttons */
.btn-send {
    margin-right: 15px; /* Adjust as needed */
}
</style>

<div class="container">
	<div class="jumbotron">
		<div class="row">
			<div class="col-md-4">
				<div class="card card-body">
					<form method="post" >
						{% csrf_token %}
						<h2 class="text-center">Reset Password</h2><hr>
						
						{% for field in form %}
								<h3>{{ field.label_tag }} 
								{{ field }}</h3>
								{% if field.errors %}
									<small>{{ field.errors|striptags  }}</small> 
								{% endif %}
						{% endfor %}<br><br><br>
						<div class="form-buttons">
							<input type="submit" value="Send" class="btn btn-primary  btn-send" style="width: 50%; height: 40px;">
							<a href="{% url 'userapp:login' %}"  class="btn btn-outline  btn-cancel" style="width: 150px; height:40px ;">Cancel</a>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
	
	</div>

{% endblock content %}

templates/password_reset_done.html
{% extends 'base.html' %}
{%block content%}

<div class="container">
	<div class="jumbotron" >
		<div class="row justify-content-center">
			<div class="col-md-6">
				<div class="card card-body">
	<center><h2>Reset Password</h2></center><hr>

	<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.

.</p>           </div>
            </div>
        </div>
    </div>
</div>

{%endblock content%}

templates/ty.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
    <div class="jumbotron">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card card-body">
                <img src="https://t4.ftcdn.net/jpg/02/02/78/81/360_F_202788149_9sndfcPPme9zRtstjROSmyLFma2UMYaM.jpg" style="height: 500px;height: 400px;">
                <h4>Thankyou for Applying!!! Your Data was Received </h4>
                <a href="{% url 'userapp:home' %}" class="btn btn-primary" style="width:200px;">Back</a>
                {{ form.as_p }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}