jobpostdata/urls.py
from django.urls import path
from jobpostdata import views

app_name = 'jobpostdata'

urlpatterns = [
    path('',views.jobdetails,name="jobdetails"),
    path('apply/<int:pk>/',views.applyuserapp,name="apply"),
    path('<int:pk>/', views.job_display, name='job_display'),
    path('appliedjobs/',views.appliedjobs, name="appliedjobs"),
]

userapp/urls.py
from django.urls import path
from userapp import views
from userapp.views import *
app_name = 'userapp'


urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('login/',views.user_login,name="login"),
    path("registration/",views.registration,name="registration"),
    path('logout/',views.user_logout,name='logout'),
    # path('apply/<int:pk>/',views.applyuserapp,name="apply"),
    path('update/',views.update,name="update"), 
    path('profile/',views.user_profile,name="profile"),
    path('ty/',views.ty,name="ty"),
    path("blogpost/",views.blogdata,name="blogpost"),
    path("blog/",views.blog,name="blog"),
    path("blogdetails/<int:id>/",views.blogdetail,name="blogdetails"),
    path("authordata/<int:user_id>/",views.authorview,name="author"),
    path("search/",views.search,name="search"),
    path("likes/<int:id>/",views.likes,name="likes"),
    path("likedata/",views.likesdata,name="likedata"),
    path('bookmark/<int:id>/', views.bookmark, name='bookmark'),
    path("bookmarkdata/",views.bookmardata,name="bookmarkdata"),
    path("forgotpassword/",views.forgotpassword,name="forgotpassword"),
    
]

userproject/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp.views import *
from django.conf.urls.static import static
from django.conf import settings


from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('',include("userapp.urls")),
    path('jobpost/',include("jobpostdata.urls")),
    path('admin/', admin.site.urls),
    path('password-reset/', PasswordResetView.as_view(template_name = "password_reset.html"),name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="password_reset_done.html"),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name='password_reset_complete'),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

userproject/userproject/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include("userapp.urls")),
    path('jobpost/',include("jobpostdata.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

templates/jobpost/jobdetails.html
{% extends "base.html" %}

{% block content %}
<body>
    <br>

    <div class="container">
        <div class="jumbotron">
            <div class="row">
                {% for job in jobs %}
                    <div class="col-md-4">
                        <div class="card card-body">
                            <h4>Title : {{ job.job_title }}</h4><hr>
                            <p>Company: {{ job.company }}</p>
                            <p><img src = "https://cdn-icons-png.flaticon.com/512/17/17736.png" style="height:20px;width:20px;"> {{job.location}}  <img src = "https://icons.veryicon.com/png/o/miscellaneous/x/my-salary.png" style="height:20px;width:20px;">  : {{job.salary}} <img src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_g4r7-apf0hG38cZ9T2ggHqkgsrjlCy9q3Gy7FjeuCC83KfU1gkb7L2cfg4KjU5myQ-E&usqp=CAU" style="height:20px;width:20px;"> : {{job.type}}</p>
                            <hr>
                            <a href="{% url 'jobpostdata:job_display' pk=job.pk %}" class="btn btn-primary">View more</a>
                        </div>   
                    </div>
                    
                    {% if forloop.counter|divisibleby:3 %}
                        </div><div class="row">
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</body>
{% endblock %}